#!/bin/bash

echo "Installing requirements for Sagan 2.0 ...."
ROS_DISTRO=humble

# Update Package List
apt-get update  

apt-get install -y ros-${ROS_DISTRO}-xacro

# Gazebo
apt-get install -y ros-${ROS_DISTRO}-gazebo-ros-pkgs

# ROS2 Control
apt-get install -y ros-${ROS_DISTRO}-ros2-control
apt-get install -y ros-${ROS_DISTRO}-ros2-controllers
apt-get install -y ros-${ROS_DISTRO}-gazebo-ros2-control
apt-get install -y ros-${ROS_DISTRO}-controller-manager
apt-get install -y ros-${ROS_DISTRO}-joint-state-broadcaster
apt-get install -y ros-${ROS_DISTRO}-diff-drive-controller

# ROS2 Navigation
apt-get install -y ros-${ROS_DISTRO}-navigation2
apt-get install -y ros-${ROS_DISTRO}-nav2-bringup